core/blog/api/v1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('post',view=views.list_api_view,name='list-api'),
    path('post/<int:id>',view=views.detail_api_view,name='detail-api')
]

core/blog/urls.py
from django.urls import path,include
from django.views.generic import TemplateView
from . import views

app_name = 'blog'

urlpatterns = [
    path('func',view=views.IndexFunc,name='func-index'),
    path('class',view=views.IndexClass.as_view(),name='class-index'),
    path('redirect',view=views.RedirectToMaktab.as_view(),name='redirect'),
    path('posts/',view=views.PostListView.as_view(),name='post-list'),
    path('posts/<int:pk>/',view=views.PostDetailView.as_view(),name='post-detail'),
    path('posts/create/',view=views.PostCreateView.as_view(),name='post-create'),
    path('posts/<int:pk>/edit/',view=views.PostEditView.as_view(),name='post-edit'),
    path('posts/<int:pk>/delete/',view=views.PostDeleteView.as_view(),name='post-delete'),
    path('api/v1/',include('blog.api.v1.urls'),name='api-v1-view')
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('api-auth/',include('rest_framework.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    ]   

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(unique=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    # is_verified = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    objects = UserManager()
    
    USERNAME_FIELD = 'email'
    
    def __str__(self):
        return self.email
    
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    image = models.ImageField(null=True,blank=True)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.email
    
@receiver(post_save,sender=User)
def save_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

core/blog/models.py
from django.db import models
#from accounts.models import Profile

#from django.contrib.auth import get_user_model
#User = get_user_model()

class Post(models.Model):
    author = models.ForeignKey('accounts.Profile',on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(null=True)
    status = models.BooleanField(default=False)
    image = models.ImageField(null=True,blank=True)

    def __str__(self):
        return self.title
    
class Category(models.Model):
    name = models.CharField(max_length=255,null=True)
    
    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('title','content','category','status','published_date')

core/accounts/views.py
from django.shortcuts import render

# Create your views here.

core/blog/api/v1/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser
from .serializers import *
from blog.models import *
from django.shortcuts import get_object_or_404

@api_view(['GET','POST'])
@permission_classes([IsAuthenticatedOrReadOnly])
def list_api_view(request):
    if request.method == 'GET':
        post = Post.objects.filter(status=1)
        serializer = PostSerializer(post,many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

@api_view(['GET','PUT','DELETE'])
def detail_api_view(request,id):
    post = get_object_or_404(Post,pk=id,status=1)
    if request.method == 'GET':
        serializer = PostSerializer(post)
        return Response(serializer.data)
    elif request.method == 'PUT':
        serializer = PostSerializer(post,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    elif request.method == 'DELETE':
        post.delete()
        return Response({'detail':'item removed'},status=status.HTTP_204_NO_CONTENT)

core/blog/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView,RedirectView
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *

def IndexFunc(request):
    return render(request ,'index.html')

class IndexClass(TemplateView):
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'ali'
        context['posts'] = Post.objects.all()
        return context

class RedirectToMaktab(RedirectView):
    pattern_name = 'blog:class-index'

class PostListView(ListView):
    queryset = Post.objects.filter(status=1)
    context_object_name = 'posts'
    paginate_by = 2
    ordering = 'created_date'
    template_name = 'blog/post-list.html'

    # def get_queryset(self):
    #     posts = Post.objects.filter(status=1)
    #     return posts
    
class PostDetailView(LoginRequiredMixin,DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post-detail.html'
    
class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post-create.html'
    success_url = '/blog/posts/'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class PostEditView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post-create.html'
    success_url = '/blog/posts/'
    
class PostDeleteView(DeleteView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post-delete.html'
    success_url = '/blog/posts/'

core/templates/blog/post-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>post form</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">submit</button>
    </form>
</body>
</html>

core/templates/blog/post-delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure to delete {{post}} ?</p>
    <input type="submit" value="Confirm">
</form>

core/templates/blog/post-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>post detail</h1>
    <h3>{{post.title}}</h3>
    <p>{{post.content}}</p>
</body>
</html>

core/templates/blog/post-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>blog posts</h1>
    <div>
        {% for post in posts %}
        <a href="{% url 'blog:post-detail' pk=post.id %}"><h2>{{post.title}}</h2></a>
        <p>name = {{post.author.first_name}}</p>
        <a href="{% url 'blog:post-edit' pk=post.id %}"><p>edit</p></a>
        <a href="{% url 'blog:post-delete' pk=post.id %}"><p>delete</p></a>
        <p>{{post.content}}</p>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>index</h1>
    <h3>{{name}}</h3>
    <h2>{{posts}}</h2>
</body>
</html>